In [1]:
import numpy as np

np.array([1,2,3,4,5])


array([1, 2, 3, 4, 5])

In [8]:
b = np.array([[1,2,3,4],[3,4,5,6]])
print(b)

[[1 2 3 4]
 [3 4 5 6]]


In [10]:
b = np.array([[1,2],[2,3],[3,4]])
print(b)

[[1 2]
 [2 3]
 [3 4]]


In [12]:
c = np.array([[[1,2],[3,4]],[[5,6],[6,7]]]) #tenser
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [13]:
np.array([1,2,3],dtype = float)

array([1., 2., 3.])

In [14]:
np.array([0,2,3],dtype = bool)

array([False,  True,  True])

In [15]:
np.array([1,2,3],dtype = complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
#np.arange  similar to range
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [45]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
np.ones((3,4))            #neural networks
                        # to initialise array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
np.random.random((3,4))

array([[0.82027399, 0.5944467 , 0.48122193, 0.03810078],
       [0.51385876, 0.15571667, 0.80853714, 0.87177628],
       [0.85667474, 0.04810545, 0.10608865, 0.68140556]])

In [27]:
#np.linspace
np.linspace(-10,10,8)

array([-10.        ,  -7.14285714,  -4.28571429,  -1.42857143,
         1.42857143,   4.28571429,   7.14285714,  10.        ])

In [28]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
import numpy as np
a1 = np.arange(10)
a2 = np.arange(12,dtype= float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a1
a2


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [4]:
#ndim            what dimension
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

NameError: name 'a1' is not defined

In [37]:
#shape           row X column
a1.shape

(10,)

In [40]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
#size           no. of elements
a3.size

8

In [42]:
#itamsize        int 64 = 8 bytes   & int 32 = 4 bytes
a1.itemsize         

8

In [44]:
#dtype
print(a1.dtype)

int64


In [46]:
 #astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [58]:
print(a1.dtype )

int64


In [55]:
a1.astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [53]:
a1.astype(bool)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [56]:
# ARRAY OPERATION

a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [59]:
# Scaler operation
# Arithmetic
a1 *2
a1/2
a1+2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [60]:
# Relational
a2 >15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [61]:
# Vector operation
# Arithmetic
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [68]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[85., 73., 40.],
       [73., 61., 51.],
       [30., 39., 29.]])

In [65]:
#max/min/sum/prod
np.max(a1)

np.float64(99.0)

In [66]:
np.sum(a1)

np.float64(548.0)

In [69]:
#0 ->col and 1 ->row
np.max(a1 ,axis =1)

array([85., 73., 39.])

In [70]:
# mean/median/std/var
np.mean(a1 ,axis = 1)

array([66.        , 61.66666667, 32.66666667])

In [71]:
# trignometry functions
np.sin(a1)


array([[-0.17607562, -0.67677196,  0.74511316],
       [-0.67677196, -0.96611777,  0.67022918],
       [-0.98803162,  0.96379539, -0.66363388]])

In [72]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 =np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [73]:
#log and exponents
np.log(a1)
np.exp(a1)

array([[4.44265126, 4.29045944, 3.68887945],
       [4.29045944, 4.11087386, 3.93182563],
       [3.40119738, 3.66356165, 3.36729583]])

In [83]:
#round / floor/ceil
np.floor(np.random.random((1,11)))
np.round(np.random.random((1,11)))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [91]:
# Indexing
z = np.arange(8).reshape(2,2,2)
z

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [92]:
z[1,0,1]

np.int64(5)

In [93]:
# Slicing
a2 = np.arange(12)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
a2[2:5]

array([2, 3, 4])

In [96]:
b

array([[1, 2],
       [2, 3],
       [3, 4]])

In [97]:
b[:,1]

array([2, 3, 4])

In [126]:
a1[1:,1:3]

array([[61., 51.]])

In [99]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
a3[0:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#

In [107]:
#iteration
a2 = np.arange(12)
for i in a2:
 print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [109]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [110]:
for i in np.nditer(a3):
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [113]:
# Transpose
np.transpose(a1)
a1.T

array([[85., 73., 30.],
       [73., 61., 39.],
       [40., 51., 29.]])

In [114]:
a1.ravel()

array([85., 73., 40., 73., 61., 51., 30., 39., 29.])

In [120]:
#Stacking
#horizontal
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [121]:
#vertical
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [122]:
#spliting
#horizontal
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [125]:
#vertical
a6 = np.arange(16).reshape(4,4)
np.vsplit(a6,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]